import dotenv from "dotenv";
dotenv.config();
import { connectDB } from "./db.js";
import Player from "./models/Player.js";

const sample = [
  {
    name: "Rohit Sharma",
    role: "Batsman",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Mumbai",
    matches: 254,
    runs: 10750,
    wickets: 0,
    average: 49.1,
    strikeRate: 90.3,
    economy: 0,
  },
  {
    name: "Virat Kohli",
    role: "Batsman",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Bangalore",
    matches: 280,
    runs: 13000,
    wickets: 4,
    average: 57.3,
    strikeRate: 93.8,
    economy: 5.9,
  },
  {
    name: "Jasprit Bumrah",
    role: "Bowler",
    battingStyle: "RHB",
    bowlingStyle: "Right-arm Fast",
    team: "Mumbai",
    matches: 120,
    runs: 200,
    wickets: 220,
    average: 8.5,
    strikeRate: 70.0,
    economy: 4.4,
  },
  {
    name: "Ravindra Jadeja",
    role: "All-Rounder",
    battingStyle: "LHB",
    bowlingStyle: "Left-arm Orthodox",
    team: "Chennai",
    matches: 240,
    runs: 3500,
    wickets: 210,
    average: 35.2,
    strikeRate: 88.1,
    economy: 4.9,
  },
  {
    name: "MS Dhoni",
    role: "Wicket-Keeper",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Chennai",
    matches: 350,
    runs: 10500,
    wickets: 0,
    average: 50.1,
    strikeRate: 89.5,
    economy: 0,
  },
  // add enough to exceed 20:
  {
    name: "Shubman Gill",
    role: "Batsman",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Gujarat",
    matches: 60,
    runs: 2300,
    wickets: 0,
    average: 49.0,
    strikeRate: 92.0,
    economy: 0,
  },
  {
    name: "Suryakumar Yadav",
    role: "Batsman",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Mumbai",
    matches: 110,
    runs: 3500,
    wickets: 0,
    average: 38.0,
    strikeRate: 140.0,
    economy: 0,
  },
  {
    name: "Hardik Pandya",
    role: "All-Rounder",
    battingStyle: "RHB",
    bowlingStyle: "Right-arm Fast",
    team: "Mumbai",
    matches: 100,
    runs: 2000,
    wickets: 80,
    average: 33.0,
    strikeRate: 130.0,
    economy: 6.8,
  },
  {
    name: "Mohammed Shami",
    role: "Bowler",
    battingStyle: "RHB",
    bowlingStyle: "Right-arm Fast",
    team: "Gujarat",
    matches: 150,
    runs: 250,
    wickets: 250,
    average: 10.0,
    strikeRate: 80.0,
    economy: 4.7,
  },
  {
    name: "Kuldeep Yadav",
    role: "Bowler",
    battingStyle: "LHB",
    bowlingStyle: "Left-arm Orthodox",
    team: "Delhi",
    matches: 90,
    runs: 300,
    wickets: 150,
    average: 12.0,
    strikeRate: 70.0,
    economy: 4.5,
  },
  {
    name: "Rishabh Pant",
    role: "Wicket-Keeper",
    battingStyle: "LHB",
    bowlingStyle: "None",
    team: "Delhi",
    matches: 100,
    runs: 3000,
    wickets: 0,
    average: 34.0,
    strikeRate: 140.0,
    economy: 0,
  },
  {
    name: "KL Rahul",
    role: "Batsman",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Lucknow",
    matches: 140,
    runs: 5200,
    wickets: 0,
    average: 45.0,
    strikeRate: 135.0,
    economy: 0,
  },
  {
    name: "Rinku Singh",
    role: "Batsman",
    battingStyle: "LHB",
    bowlingStyle: "None",
    team: "Kolkata",
    matches: 50,
    runs: 1200,
    wickets: 0,
    average: 40.0,
    strikeRate: 145.0,
    economy: 0,
  },
  {
    name: "Yuzvendra Chahal",
    role: "Bowler",
    battingStyle: "RHB",
    bowlingStyle: "Leg-spin",
    team: "Rajasthan",
    matches: 130,
    runs: 200,
    wickets: 220,
    average: 9.0,
    strikeRate: 60.0,
    economy: 4.8,
  },
  {
    name: "Axar Patel",
    role: "All-Rounder",
    battingStyle: "LHB",
    bowlingStyle: "Left-arm Orthodox",
    team: "Delhi",
    matches: 140,
    runs: 2200,
    wickets: 160,
    average: 29.0,
    strikeRate: 125.0,
    economy: 5.5,
  },
  {
    name: "Prithvi Shaw",
    role: "Batsman",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Delhi",
    matches: 70,
    runs: 1800,
    wickets: 0,
    average: 30.0,
    strikeRate: 140.0,
    economy: 0,
  },
  {
    name: "Ishan Kishan",
    role: "Wicket-Keeper",
    battingStyle: "LHB",
    bowlingStyle: "None",
    team: "Mumbai",
    matches: 95,
    runs: 2600,
    wickets: 0,
    average: 32.0,
    strikeRate: 137.0,
    economy: 0,
  },
  {
    name: "Ravichandran Ashwin",
    role: "All-Rounder",
    battingStyle: "RHB",
    bowlingStyle: "Off-spin",
    team: "Rajasthan",
    matches: 200,
    runs: 3500,
    wickets: 340,
    average: 26.0,
    strikeRate: 90.0,
    economy: 4.2,
  },
  {
    name: "Shardul Thakur",
    role: "Bowler",
    battingStyle: "RHB",
    bowlingStyle: "Right-arm Fast",
    team: "Kolkata",
    matches: 110,
    runs: 1200,
    wickets: 130,
    average: 18.0,
    strikeRate: 95.0,
    economy: 6.9,
  },
  {
    name: "Sanju Samson",
    role: "Wicket-Keeper",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Rajasthan",
    matches: 140,
    runs: 4200,
    wickets: 0,
    average: 35.0,
    strikeRate: 135.0,
    economy: 0,
  },
  {
    name: "Rahul Tripathi",
    role: "Batsman",
    battingStyle: "RHB",
    bowlingStyle: "None",
    team: "Hyderabad",
    matches: 90,
    runs: 2100,
    wickets: 0,
    average: 31.0,
    strikeRate: 138.0,
    economy: 0,
  },
  {
    name: "Bhuvneshwar Kumar",
    role: "Bowler",
    battingStyle: "RHB",
    bowlingStyle: "Right-arm Fast",
    team: "Hyderabad",
    matches: 160,
    runs: 400,
    wickets: 220,
    average: 12.0,
    strikeRate: 70.0,
    economy: 4.9,
  },
  {
    name: "S Mohammed Siraj",
    role: "Bowler",
    battingStyle: "RHB",
    bowlingStyle: "Right-arm Fast",
    team: "Bangalore",
    matches: 120,
    runs: 200,
    wickets: 170,
    average: 11.5,
    strikeRate: 72.0,
    economy: 5.2,
  },
  {
    name: "Tilak Varma",
    role: "Batsman",
    battingStyle: "LHB",
    bowlingStyle: "None",
    team: "Mumbai",
    matches: 35,
    runs: 950,
    wickets: 0,
    average: 36.0,
    strikeRate: 139.0,
    economy: 0,
  },
];

async function run() {
  await connectDB();
  await Player.deleteMany({});
  await Player.insertMany(sample);
  console.log(`✅ Seeded ${sample.length} players`);
  process.exit(0);
}
run().catch((e) => {
  console.error(e);
  process.exit(1);
});
